/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.DepartamentoControlador;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import Modelo.Departamento;
import Modelo.Empresa;
import javax.swing.JOptionPane;

/**
 *
 * @author NOTEBOOK
 */
public class DepartamentoVista extends javax.swing.JInternalFrame {

    private Departamento departamento;
    final DepartamentoControlador departamentoControlador;
    
    private TableModel modeloTablaDepartamentos;
    
    public DepartamentoVista() {
        initComponents();
        departamentoControlador =  new DepartamentoControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCodigoDepartamento = new javax.swing.JTextField();
        jTextFieldNombreDepartamento = new javax.swing.JTextField();
        jButtonAgregarDepartamento = new javax.swing.JButton();
        jButtonMostrarDepartamentos = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxEmpresasDepartamento = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldUbicacionDepartamento = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDep = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Departamentos");

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel14.setText("Codigo");

        jLabel15.setText("Nombre");

        jTextFieldCodigoDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoDepartamentoKeyReleased(evt);
            }
        });

        jButtonAgregarDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonAgregarDepartamento.setText("AGREGAR");
        jButtonAgregarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarDepartamentoActionPerformed(evt);
            }
        });

        jButtonMostrarDepartamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonMostrarDepartamentos.setText("MOSTRAR");
        jButtonMostrarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDepartamentosActionPerformed(evt);
            }
        });

        jLabel17.setText("Empresa");

        jComboBoxEmpresasDepartamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxEmpresasDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Datos" }));
        jComboBoxEmpresasDepartamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxEmpresasDepartamentoFocusGained(evt);
            }
        });

        jLabel18.setText("Ubicacion");

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTableDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Gerente", "Empresa", "Ubicacion"
            }
        ));
        jScrollPane1.setViewportView(jTableDep);

        jButton1.setText("EDITAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BORRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAgregarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMostrarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigoDepartamento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNombreDepartamento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxEmpresasDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldUbicacionDepartamento, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButton1)
                .addGap(77, 77, 77)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldCodigoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxEmpresasDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUbicacionDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostrarDepartamentos)
                    .addComponent(jButtonAgregarDepartamento))
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoDepartamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoDepartamentoKeyReleased
        if (!departamentoControlador.validarSoloNumeros(evt.getKeyChar())) {
            if(jTextFieldCodigoDepartamento.getText().length() > 0){
                String temp =jTextFieldCodigoDepartamento.getText().substring(0,jTextFieldCodigoDepartamento.getText().length()-1);
                jTextFieldCodigoDepartamento.setText(temp);
            }
        }
    }//GEN-LAST:event_jTextFieldCodigoDepartamentoKeyReleased

    private void jButtonAgregarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarDepartamentoActionPerformed
       
        agregar();
        clearDepartamento();
        mostrarTablaDepartamentos();
        JOptionPane.showMessageDialog(this, "Departamento Agregado!");
        
    }//GEN-LAST:event_jButtonAgregarDepartamentoActionPerformed

    private void jButtonMostrarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDepartamentosActionPerformed
        System.out.println("DEPARTAMENTOS:\n");
        for (Departamento dep : departamentoControlador.listarDepartamentos()) {
            System.out.println(dep.mostrarInformacion());
            System.out.println("");
        }
        
        System.out.println("----------------------------------------------------------------------");

        mostrarTablaDepartamentos();
   
    }//GEN-LAST:event_jButtonMostrarDepartamentosActionPerformed

    private void jComboBoxEmpresasDepartamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxEmpresasDepartamentoFocusGained
        cargarEmpresaCombo();
    }//GEN-LAST:event_jComboBoxEmpresasDepartamentoFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      editar(jTableDep.getSelectedRow());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      /** departamentoControlador.eliminarDepartamento(this.departamento.getCodigo());
        System.out.println("Deparatemento Eliminado");
        this.dispose();
        * */
      String arg;
        arg=this.jTextFieldCodigoDepartamento.getText();
        this.departamentoControlador.eliminar(arg);
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void agregar(){
         var departamentoNuevo = departamentoControlador.crearDepartamento(Integer.parseInt(jTextFieldCodigoDepartamento.getText()), 
                jTextFieldNombreDepartamento.getText(), getEmpresaFromComboBox(), jTextFieldUbicacionDepartamento.getText());
       
       
    }
    
    private Empresa getEmpresaFromComboBox(){
        if (!this.jComboBoxEmpresasDepartamento.getSelectedItem().toString().equalsIgnoreCase("Sin Datos")){
            Empresa em = departamentoControlador.empresaServicio.listarEmpresas().get(jComboBoxEmpresasDepartamento.getSelectedIndex());
            return em;
        }
        
        return null;
    }
    
     private void clearDepartamento(){
        jTextFieldCodigoDepartamento.setText("");
        jTextFieldNombreDepartamento.setText("");
        jTextFieldUbicacionDepartamento.setText("");
        
    }
    
    private void cargarEmpresaCombo(){
      jComboBoxEmpresasDepartamento.removeAllItems();
        for(var empresa: departamentoControlador.empresaServicio.listarEmpresas()){
            jComboBoxEmpresasDepartamento.addItem(empresa.getNombre());
        }
    }
     
     private void mostrarTablaDepartamentos(){
        var header = new String[5];
        
        header[0] = "Codigo";
        header[1] = "Nombre";
        header[2] = "Empresa";
        header[3] = "Ubicacion";
        
        var data = new Object[this.departamentoControlador.listarDepartamentos().size()][5];
        
        for (int i = 0; i < this.departamentoControlador.listarDepartamentos().size(); i++) {
            data[i][0] = this.departamentoControlador.listarDepartamentos().get(i).getCodigo();
            data[i][1] = this.departamentoControlador.listarDepartamentos().get(i).getNombre();
            
            if (this.departamentoControlador.listarDepartamentos().get(i).getGerente() == null){
                data[i][2] = "Sin Gerente";
            } else{
                 data[i][2] = this.departamentoControlador.listarDepartamentos().get(i).getGerente().getNombre();
            }
           
            data[i][3] = this.departamentoControlador.listarDepartamentos().get(i).getEmpresa().getNombre();
            data[i][4] = this.departamentoControlador.listarDepartamentos().get(i).getUbicacion();
        }
        
        this.modeloTablaDepartamentos = new DefaultTableModel(data, header);
        this.jTableDep.setModel(modeloTablaDepartamentos);
    }
    
    private void editar(int posicion){
        DepartamentoVistaEdicion departamentoVentanaEdicion = new DepartamentoVistaEdicion(this.departamentoControlador.listarDepartamentos().get(posicion));
        departamentoVentanaEdicion.setLocationRelativeTo(this);
        departamentoVentanaEdicion.setVisible(true);
    }
     
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartamentoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgregarDepartamento;
    private javax.swing.JButton jButtonMostrarDepartamentos;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JComboBox<String> jComboBoxEmpresasDepartamento;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableDep;
    private javax.swing.JTextField jTextFieldCodigoDepartamento;
    private javax.swing.JTextField jTextFieldNombreDepartamento;
    private javax.swing.JTextField jTextFieldUbicacionDepartamento;
    // End of variables declaration//GEN-END:variables
}
